name: fila_certa_app
description: "Fila Certa — protótipo de gestão inteligente de filas e atendimento."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  geolocator: ^13.0.1
  supabase_flutter: ^2.8.0
  sentry_flutter: ^8.14.2
  flutter_svg: ^2.0.10
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
