// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GYgxawqD5SzmEPdTzfKg4iKbaPyLcqA',
    appId: '1:786280071370:web:ee14e7a798326ab6fe7433',
    messagingSenderId: '786280071370',
    projectId: 'filacerta-d74f0',
    authDomain: 'filacerta-d74f0.firebaseapp.com',
    storageBucket: 'filacerta-d74f0.firebasestorage.app',
    measurementId: 'G-9XN929Z452',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQW0dUdHu5ppSaGlPRrJSsLrlWsIs5W9A',
    appId: '1:786280071370:android:4e630530bbce7fddfe7433',
    messagingSenderId: '786280071370',
    projectId: 'filacerta-d74f0',
    storageBucket: 'filacerta-d74f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtBKMIrrmktQPSgBiWwZhwcylPbeFKPKc',
    appId: '1:786280071370:ios:8ad272c4ba419b32fe7433',
    messagingSenderId: '786280071370',
    projectId: 'filacerta-d74f0',
    storageBucket: 'filacerta-d74f0.firebasestorage.app',
    iosClientId: '786280071370-fjj86s2ohodgdjcjlctnhqqncbu9pp60.apps.googleusercontent.com',
    iosBundleId: 'com.example.filaCertaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtBKMIrrmktQPSgBiWwZhwcylPbeFKPKc',
    appId: '1:786280071370:ios:8ad272c4ba419b32fe7433',
    messagingSenderId: '786280071370',
    projectId: 'filacerta-d74f0',
    storageBucket: 'filacerta-d74f0.firebasestorage.app',
    iosClientId: '786280071370-fjj86s2ohodgdjcjlctnhqqncbu9pp60.apps.googleusercontent.com',
    iosBundleId: 'com.example.filaCertaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7GYgxawqD5SzmEPdTzfKg4iKbaPyLcqA',
    appId: '1:786280071370:web:9e1b4193d76ebeb6fe7433',
    messagingSenderId: '786280071370',
    projectId: 'filacerta-d74f0',
    authDomain: 'filacerta-d74f0.firebaseapp.com',
    storageBucket: 'filacerta-d74f0.firebasestorage.app',
    measurementId: 'G-BT48R6LE16',
  );
}
